[package]
name = "netavark"
version = "1.0.4-dev"
edition = "2018"
authors = ["github.com/containers"]
description = "A container network stack"
exclude = ["/.cirrus.yml", "/.github/*", "/hack/*"]
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["serde", "deps-serde"]
deps-serde = ["chrono/serde", "url/serde"]

[dependencies]
anyhow = "1.0"
chrono = "0.4.7"
clap = { version = "3.0.12", features = ["derive"] }
env_logger = "0.9.0"
ipnet = { version = "2", features = ["serde"] }
iptables = "0.5"
libc = "0.2"
log = "0.4.17"
serde = { version = "1.0.137", features = ["derive"], optional = true }
serde-value = "0.7.0"
serde_json = "1.0.81"
simple-error = "0.2.3"
sysctl = "0.4.4"
url = "2.1.0"
zbus = "2.2.0"
rtnetlink = "0.9.0"
futures = "0.3.21"
nix = "0.24.1"
rand = "0.8.5"
tokio = { version = "1.19.2", features = ["full"] }
zvariant = "3.3.1"
sha2 = "0.10.1"
netlink-packet-route = "0.11"

[build-dependencies]
chrono = "*"
