[package]
name = "netavark"
version = "1.12.1"
edition = "2021"
authors = ["github.com/containers"]
license = "Apache-2.0"
readme = "README.md"
description = "A container network stack"
homepage = "https://github.com/containers/netavark"
repository = "https://github.com/containers/netavark"
categories = ["virtualization"]
exclude = ["/.cirrus.yml", "/.github/*", "/hack/*"]
build = "build.rs"

[package.metadata.vendor-filter]
platforms = ["*-unknown-linux-*"]
tier = "2"

[[bin]]
name = "netavark"
path = "src/main.rs"

[[bin]]
name = "netavark-dhcp-proxy-client"
path = "src/dhcp_proxy_client/client.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["serde", "deps-serde"]
deps-serde = ["chrono/serde", "url/serde"]

[dependencies]
anyhow = "1.0.86"
clap = { version = "~4.4.12", features = ["derive", "env"] }
env_logger = "0.11.5"
ipnet = { version = "2.9.0", features = ["serde"] }
iptables = "0.5.2"
libc = "0.2.154"
log = "0.4.22"
serde = { version = "1.0.199", features = ["derive"], optional = true }
serde-value = "0.7.0"
serde_json = "1.0.121"
sysctl = "0.5.5"
url = "2.5.2"
zbus = { version = "3.15.2" }
nix = { version = "0.29.0", features = ["sched", "signal", "user"] }
rand = "0.8.5"
sha2 = "0.10.8"
netlink-packet-utils = "0.5.2"
netlink-packet-route = "0.20.1"
netlink-packet-core = "0.7.0"
nftables = "0.4.1"
fs2 = "0.4.3"
netlink-sys = "0.8.6"
tokio = { version = "1.39.2", features = ["rt", "rt-multi-thread", "signal", "fs"] }
tokio-stream = { version = "0.1.15", features = ["net"] }
tonic = "0.11"
mozim = "0.2.4"
prost = "0.12.6"
futures-channel = "0.3.30"
futures-core = "0.3.30"
futures-util = "0.3.30"
nispor = "1.2.19"
tower = { version = "0.4.13" }

[build-dependencies]
chrono = { version = "0.4.38", default-features = false, features = ["clock"] }
tonic-build = "0.11"

[dev-dependencies]
once_cell = "1.19.0"
rand = "0.8.5"
tempfile = "3.10.1"
