[package]
name = "netavark"
version = "1.6.0-dev"
edition = "2018"
authors = ["github.com/containers"]
license = "Apache-2.0"
readme = "README.md"
description = "A container network stack"
homepage = "https://github.com/containers/netavark"
repository = "https://github.com/containers/netavark"
categories = ["containers", "networking", "podman"]
exclude = ["/.cirrus.yml", "/.github/*", "/hack/*"]
build = "build.rs"

[package.metadata.vendor-filter]
# This list is not exhaustive.
platforms = ["x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu", "powerpc64le-unknown-linux-gnu", 
             "s390x-unknown-linux-gnu", "riscv64gc-unknown-linux-gnu",
             "x86_64-unknown-linux-musl", "aarch64-unknown-linux-musl",
             ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["serde", "deps-serde"]
deps-serde = ["chrono/serde", "url/serde"]

[dependencies]
anyhow = "1.0"
clap = { version = "3.2.23", features = ["derive"] }
env_logger = "0.10.0"
ipnet = { version = "2", features = ["serde"] }
iptables = "0.5"
libc = "0.2"
log = "0.4.17"
serde = { version = "1.0.152", features = ["derive"], optional = true }
serde-value = "0.7.0"
serde_json = "1.0.91"
sysctl = "0.5.4"
url = "2.3.1"
zbus = { version = "3.8.0" }
nix = "0.26.2"
rand = "0.8.5"
sha2 = "0.10.6"
netlink-packet-route = "0.13"
netlink-packet-core = "0.4.2"
fs2 = "0.4.3"
netlink-sys = "0.8.3"
netavark_proxy = { git = "https://github.com/containers/netavark-dhcp-proxy"} 
tokio = { version = "1.25", features = ["rt"] }

[build-dependencies]
chrono = { version = "0.4.22", default-features = false, features = ["clock"] }
