[package]
name = "netavark"
version = "1.14.0-dev"
edition = "2021"
authors = ["github.com/containers"]
license = "Apache-2.0"
readme = "README.md"
description = "A container network stack"
homepage = "https://github.com/containers/netavark"
repository = "https://github.com/containers/netavark"
categories = ["virtualization"]
exclude = ["/.cirrus.yml", "/.github/*", "/hack/*"]
build = "build.rs"
rust-version = "1.76"

[package.metadata.vendor-filter]
platforms = ["*-unknown-linux-*"]
tier = "2"

[[bin]]
name = "netavark"
path = "src/main.rs"

[[bin]]
name = "netavark-dhcp-proxy-client"
path = "src/dhcp_proxy_client/client.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["serde", "deps-serde"]
deps-serde = ["chrono/serde", "url/serde"]

[dependencies]
anyhow = "1.0.93"
clap = { version = "~4.5.23", features = ["derive", "env"] }
env_logger = "0.11.6"
ipnet = { version = "2.11.0", features = ["serde"] }
iptables = "0.5.2"
libc = "0.2.157"
log = "0.4.24"
serde = { version = "1.0.213", features = ["derive"], optional = true }
serde-value = "0.7.0"
serde_json = "1.0.136"
sysctl = "0.6.0"
url = "2.5.3"
zbus = { version = "4.3.1" }
nix = { version = "0.29.0", features = ["sched", "signal", "user"] }
rand = "0.8.5"
sha2 = "0.10.8"
netlink-packet-utils = "0.5.2"
netlink-packet-route = "0.21.0"
netlink-packet-core = "0.7.0"
nftables = "0.6.0"
fs2 = "0.4.3"
netlink-sys = "0.8.7"
tokio = { version = "1.43.0", features = ["rt", "rt-multi-thread", "signal", "fs"] }
tokio-stream = { version = "0.1.17", features = ["net"] }
tonic = "0.12.3"
mozim = "0.2.5"
prost = "0.13.4"
futures-channel = "0.3.31"
futures-core = "0.3.31"
futures-util = "0.3.31"
nispor = "1.2.22"
tower = { version = "0.5.2", features = ["util"] }
hyper-util = "0.1.10"

[build-dependencies]
chrono = { version = "0.4.39", default-features = false, features = ["clock"] }
tonic-build = "0.12.3"

[dev-dependencies]
once_cell = "1.20.2"
rand = "0.8.5"
tempfile = "3.15.0"
