[package]
name = "netavark"
version = "1.8.0-dev"
edition = "2018"
authors = ["github.com/containers"]
license = "Apache-2.0"
readme = "README.md"
description = "A container network stack"
homepage = "https://github.com/containers/netavark"
repository = "https://github.com/containers/netavark"
categories = ["containers", "networking", "podman"]
exclude = ["/.cirrus.yml", "/.github/*", "/hack/*"]
build = "build.rs"

[package.metadata.vendor-filter]
# This list is not exhaustive.
platforms = ["x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu", "powerpc64le-unknown-linux-gnu",
             "s390x-unknown-linux-gnu", "riscv64gc-unknown-linux-gnu",
             "x86_64-unknown-linux-musl", "aarch64-unknown-linux-musl",
             ]

[[bin]]
name = "netavark"
path = "src/main.rs"

[[bin]]
name = "netavark-dhcp-proxy-client"
path = "src/dhcp_proxy_client/client.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["serde", "deps-serde"]
deps-serde = ["chrono/serde", "url/serde"]

[dependencies]
anyhow = "1.0"
clap = { version = "4.3.11", features = ["derive"] }
env_logger = "0.10.0"
ipnet = { version = "2", features = ["serde"] }
iptables = "0.5"
libc = "0.2"
log = "0.4.19"
serde = { version = "1.0.171", features = ["derive"], optional = true }
serde-value = "0.7.0"
serde_json = "1.0.103"
sysctl = "0.5.4"
url = "2.4.0"
zbus = { version = "3.14.1" }
nix = "0.26.2"
rand = "0.8.5"
sha2 = "0.10.7"
netlink-packet-utils = "0.5.2"
netlink-packet-route = "0.17.0"
netlink-packet-core = "0.7.0"
fs2 = "0.4.3"
netlink-sys = "0.8.5"
tokio = { version = "1.29", features = ["rt", "rt-multi-thread", "signal", "fs"] }
tokio-stream = { version = "0.1", features = ["net"] }
tonic = "0.9"
mozim = "0.2.2"
prost = "0.11"
futures-channel="0.3.28"
futures-core = "0.3.28"
futures-util = "0.3.28"
nispor = "1.2.12"
http = "0.2.9"
tower = { version = "0.4" }

[build-dependencies]
chrono = { version = "0.4.26", default-features = false, features = ["clock"] }
tonic-build = "0.8"

[dev-dependencies]
once_cell = "1.18.0"
rand = "0.8.5"
