[package]
name = "netavark"
version = "0.0.1"
edition = "2018"
authors = ["github.com/containers"]
description = "A container network stack"
exclude = ["/.cirrus.yml", "/.github/*", "/hack/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["serde", "deps-serde"]
deps-serde = ["chrono/serde", "url/serde"]

[dependencies]
anyhow = "1.0"
chrono = "0.4.7"
clap = "3.0.0-beta.4"
env_logger = "0.9.0"
ipnet = { version = "2", features = ["serde"] }
iptables = "0.4.3"
libc = "0.2"
log = "0.4.14"
serde = { version = "1.0.131", features = ["derive"], optional = true }
serde-value = "0.7.0"
serde_json = "1.0.72"
simple-error = "0.2.3"
sysctl = "0.4.3"
url = "2.1.0"
zbus = "1.9.1"
rtnetlink = { git = "https://github.com/little-dude/netlink", branch = "master" }
futures = "0.3.18"
nix = "0.23.0"
rand = "0.8.3"
faccess = "0.2.3"
tokio = { version = "1.14.0", features = ["full"] }
zvariant = "2.10.0"
sha2 = "0.10.0"
netlink-packet-route = "0.8.0"
