---

on:
  # Note: This only applies to the default branch.
  schedule:
    # N/B: This should correspond to a period slightly after
    # the last job finishes running.  See job defs. at:
    # https://cirrus-ci.com/settings/repository/5138144844840960
    - cron:  '59 23 * * 1-5'
  # Debug: Allow triggering job manually in github-actions WebUI
  workflow_dispatch: {}

jobs:
  # Ref: https://docs.github.com/en/actions/using-workflows/reusing-workflows
  call_cron_failures:
    uses: containers/buildah/.github/workflows/check_cirrus_cron.yml@main
    secrets: inherit
